people/urls.py
from django.urls import path 
from . import views 

app_name = 'people' 

urlpatterns = [ 
	path('person/', views.PersonDetailView.as_view(), name='personDetail'),
	path('person/setup/', views.PersonCreateView.as_view(), name='personSetUp'),
	path('person/edit/', views.PersonUpdateView.as_view(), name='personUpdate'),
]

pgp_mis/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url 
from . import views 

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('programming.urls')),
    url(r'^', include('people.urls')),
    url(r'^', include('staffing.urls')),
    path('', include('django.contrib.auth.urls')),
    path('register/', views.UserRegisterView.as_view(), name='userRegister'),
]

admin.site.site_header = "Paradise MIS Admin"
admin.site.site_title = "Paradise Green MIS 2.0"
admin.site.index_title = "Paradise Green MIS 2.0"

programming/urls.py
from django.urls import path 
from . import views 

app_name = 'programming' 

urlpatterns = [ 

	path('', views.HomeView.as_view(), name='programmingDashboard'),
	path('shows/', views.ShowListView.as_view(), name='programmingShowList'), # Uses the "current" Event 
	path('shows/pending/', views.ShowListPendingView.as_view(), name='programmingShowPending'),
	path('shows/<int:pk>/', views.ShowDetailView.as_view(), name='programmingShowDetail'),
	path('shows/<int:pk>/edit/', views.ShowUpdateView.as_view(), name='programmingShowUpdate'),

	path('shows/<int:pk>/newslot/', views.SlotCreateView.as_view(), name='programmingSlotCreation'),
	path('shows/<int:pk>/slots/', views.SlotListView.as_view(), name='programmingSlotList'),

	path('shows/<int:pk>/<int:slot_pk>/offer/', views.OfferCreateView.as_view(), name='programmingSlotOffer'),
	path('shows/<int:pk>/offer/', views.OfferUpdateView.as_view(), name='programmingOfferUpdate'),
	# path('shows/<int:pk>/offer/confirm/', views.SlotOfferConfirm.as_view(), name='programmingSlotOfferConfirm'),
	
	path('companies/', views.CompanyListView.as_view(), name='programmingCompanyList'),
	path('companies/<int:pk>/', views.CompanyDetailView.as_view(), name='programmingCompanyDetail'),
	path('companies/<int:pk>/edit/', views.CompanyFormView.as_view(), name='programmingCompanyForm'),
	path('companies/<int:pk>/invoices/', views.CompanyInvoiceView.as_view(), name='programmingCompanyInvoice'),
	
	path('invoices/', views.InvoiceListView.as_view(), name='programmingInvoiceList'),
	path('invoices/<int:pk>/', views.InvoiceDetailView.as_view(), name='programmingInvoiceDetail'),
	
	path('event/', views.EventListView.as_view(), name='programmingEventList'), # Lists all events for archive use 
	path('event/<int:pk>/', views.ShowListView.as_view(), name='programmingEventDetail'), # Same as programmingShowList but specific Event
	path('event/<int:pk>/all/', views.EventAllView.as_view(), name='programmingEventAll'),
	
	path('event/<int:pk>/perform/', views.ShowCreateView.as_view(), name='programmingCreateShow'),
	# shows/ 
	# show/<int:pk>
		# with functionality to view their slot preferences and make them an offer 
		# with functionality to view a list of invoices associated with the show 
		# with functionality to do comments / voting 
	# companies/
	# companies/<int:pk>/
	# companies/<int:pk/invoices/ - invoices for a given company 
	# invoices/ 
	# invoices/<int:pk>/ - specific invoices 
	# event/ - event list 
	# event/<int:pk>/ - shows that have been offered a slot 
	# event/<int:pk>/all/ - all shows registered with the event
]

staffing/urls.py
from django.urls import path 
from . import views 


app_name = 'staffing' 

urlpatterns = [ 
	
	path('event/<int:pk>/volunteer/', views.ApplicationFormView.as_view(), name='staffingCreateApplication'),
	path('applications/', views.ApplicationListView.as_view(), name='staffingApplicationList'), # current event 
	path('applications/<int:pk>/', views.ApplicationDetailView.as_view(), name='staffingApplicationDetail'),
	path('applications/<int:pk>/offer/', views.OfferFormView.as_view(), name='staffingApplicationOfferCreate'),
	path('applications/<int:pk>/review/', views.OfferUpdateView.as_view(), name='staffingApplicationOfferUpdate'),
	# path('event/<int:pk>/applications', views.ApplicationListView.as_view(), name='staffingAppliationListArchive'),

]

programming/models.py
import datetime 
from django.db import models

# Create your models here.

class Week(models.Model):
	class Meta:
		constraints = [
			models.UniqueConstraint(fields=['title', 'event'], name='unique_weeks_in_event')
		]

	title = models.CharField(max_length=50,
		choices = (
			('W0', 'Week 0 Start'),
			('W1', 'Week 1 Start'),
			('W2', 'Week 2 Start'),
			('W3', 'Week 3 Start'),
			('W4', 'Week 4 Start'),
		),
	)
	date = models.DateField()
	event = models.ForeignKey('Event', on_delete=models.CASCADE)
	offers_preview = models.BooleanField(default=False)
	has_performances = models.BooleanField(default=True, help_text="Whether there are performances on this week. Eg W0 and W4 will likely not.")

	def __str__(self):
		return self.title + ' for ' + str(self.event) + ' (starts ' + str(self.date) + ')'

class Event(models.Model):
	class Meta:
		ordering = ['year']

	title = models.CharField(max_length=250, default='Edinburgh Fringe', help_text='What is the event? (Typically you won\'t change this)')
	year = models.IntegerField(unique=True, null=True, help_text='The year the event is taking place. The latest year will be used as the default year for "current" lists.')
	accepting_show_submissions = models.BooleanField(default=True, help_text="Accepting submissions for show registration")
	accepting_staff_applications = models.BooleanField(default=False, help_text="Accepting applications for staff")

	def __str__(self):
		if self.year:
			return self.title + ' ' + str(self.year)
		else:
			return self.title

class Company(models.Model):
	class Meta: 
		verbose_name = 'Performing Company'
		verbose_name_plural = 'Performing Companies'

	company_name = models.CharField(
		max_length=50
	)
	company_email = models.CharField(
		max_length=150
	)
	company_website = models.CharField(
		max_length=200,
		blank=True
	)
	lead_contact = models.ForeignKey('people.Person', on_delete=models.SET_NULL, null=True, related_name='lead_contact', limit_choices_to={'person_type':'COMPY'})
	company_members = models.ManyToManyField('people.Person', related_name='company_members', blank=True, limit_choices_to={'person_type':'COMPY'})

	def get_shows(self):
		return Show.objects.filter(company=self)

	def save(self, *args, **kwargs):
		# Ensure that the lead contact is a company member. Rather than invalidating the form, we'll just add them if they've not been selected 
		# Note: This won't work in the admin :eyeroll: 
		super(Company, self).save(*args, **kwargs)
		self.company_members.add(self.lead_contact)

	def __str__(self):
		return self.company_name

class Venue(models.Model):
	class Meta:
		ordering = ['title']

	title = models.CharField(max_length = 20, help_text="The short name, eg A1", unique=True)
	full_name = models.CharField(max_length=100, help_text="The long name, eg The Sanctuary")
	parent_venue = models.CharField(
		max_length=30,
		choices = (
			('AUG', 'Paradise in Augustines'),
			('VAU', 'Paradise in The Vault'),),
		default='AUG'
	)

	def __str__(self):
		return self.full_name + ' (' + self.title + ')'


class Offer(models.Model):
	class Meta:
		permissions = [ 
			('dir_can_make_offer', 'Can make offer')
		]
	show = models.OneToOneField('Show', on_delete=models.CASCADE, null=True)
	slot = models.OneToOneField('Slot', on_delete=models.CASCADE, null=True)
	status = models.CharField(max_length=10,
		choices = (
			('PEN', 'Pending'),
			('ACC', 'Accepted'),
			('REJ', 'Rejected'),
		),
		default = 'PEN'
	)	

	def __str__(self):
		return str(self.get_status_display()) + ' offer for ' + str(self.show)

class Show(models.Model):
	class Meta:
		permissions = [ 
			('dir_can_administrate_shows', 'Can be administrator of a show')
		]

	show_title = models.CharField(max_length=200)
	company = models.ForeignKey(Company, on_delete=models.PROTECT, null=True, blank=True)
	lead_contact = models.ForeignKey('people.Person', on_delete=models.SET_NULL, null=True, related_name='show_lead_contact')
	# The lead contact for the show and the company might be different 
	status = models.CharField(
		max_length=30,
		choices = (
			('DRA', 'Draft'),
			('APP', 'Application Submitted (waiting for an offer)'),
			('COM', 'Complete'),
		),
		default = 'DRA',
		help_text = 'Application status',
	)
	level = models.CharField(
		max_length=30,
		choices = (
			('PRO', 'Professional'),
			('EME', 'Emerging Professional'),
			('SEM', 'Semi-Professional'),
			('AMA', 'Amateur'),
		),
		default = 'PRO',
		help_text = 'How established is the company?'
	)
	outline = models.TextField(blank=True) 
	motivation = models.TextField(blank=True)
	funding = models.TextField(blank=True)
	copy_short = models.TextField(blank=True, help_text="Around 50 words", verbose_name="Marketing copy (short)")
	copy_long = models.TextField(blank=True, help_text="Around 100 words", verbose_name="Marketing copy (long)")
	set_outline = models.TextField(blank=True)
	tech_outline = models.TextField(blank=True)
	cast_size = models.IntegerField(default=0)
	crew_size = models.IntegerField(default=0)
	show_duration = models.DurationField(default=0) 
	get_in_dur = models.DurationField(default=0, verbose_name="Get-in duration") 
	get_out_dur = models.DurationField(default=0, verbose_name="Get-out duration")
	event = models.ForeignKey(Event, on_delete=models.PROTECT)
	notes_general = models.TextField(blank=True, verbose_name="Notes (general)")
	via_link = models.CharField(max_length=200, blank=True, verbose_name='VIA Box Office Link')
	poster = models.ImageField(blank=True, null=True)

	def get_people(self):
		defined_people = PersonShow.objects.filter(show=self)
		return defined_people.union(self.lead_contact)

	def get_slots(self):
		return Slot.objects.filter(show=self) or None 

	def get_slot_preferences(self):
		if self.get_slots():
			prefs = [] 
			for s in self.get_slots():
				prefs.append(s.slot_preference)
			return prefs 
		else:
			return 0 

	def get_comments(self):
		return Comment.objects.filter(show=self) or None 

	def get_votes(self):
		return Vote.objects.filter(show=self) or None 

	def __str__(self):
		return_string = self.show_title
		if self.company:
			return_string += ' from ' + str(self.company)
		return return_string

class Slot(models.Model):
	class Meta:
		ordering = ['show', 'slot_preference']
		constraints = [
			models.UniqueConstraint(fields=['show', 'slot_preference'], name='unique_slot_preference')
		]

	show = models.ForeignKey(Show, on_delete=models.CASCADE, null=True)
	venue = models.ForeignKey(Venue, on_delete=models.SET_NULL, null=True)
	show_start_time = models.TimeField(help_text='SHOW, not slot, start time', null=True)
	show_end_time = models.TimeField(help_text='SHOW, not slot, end time', null=True)
	slot_price = models.DecimalField(max_digits=8, decimal_places=2,null=True,blank=True)
	slot_guarantee = models.DecimalField(max_digits=8, decimal_places=2,null=True,blank=True)
	box_office = models.DecimalField(max_digits=8, decimal_places=2,null=True,blank=True)
	slot_preference = models.PositiveSmallIntegerField(default=1)
	has_preview = models.BooleanField(default=False, verbose_name='Add a preview performance')
	slot_status = models.CharField(max_length=20,
		choices = (
			('REQ', 'Requested'),
			('OFF', 'Offered'),
			('ACC', 'Accepted'),
			('REJ', 'Rejected')),
		default='REQ')

	week = models.ManyToManyField(Week)
	# Add validator that only shows in available weeks can have a preview 

	def show_duration(self):
		return self.show.duration 
	# Need to make a datetime object, give it the times, and then do the math
	def slot_timings(self):
		start_date = self.week.first().date
		datetime_show = datetime.datetime(start_date.year, start_date.month, start_date.day) 
		datetime_show_start = datetime_show.replace(hour=self.show_start_time.hour, minute=self.show_start_time.minute)
		datetime_show_end = datetime_show.replace(hour=self.show_end_time.hour, minute=self.show_end_time.minute)

		timings = {} 
		timings['slot_start_time'] = datetime_show_start - self.show.get_in_dur
		timings['slot_end_time'] = datetime_show_end - self.show.get_out_dur 
		timings['slot_duration'] = timings['slot_start_time'] - timings['slot_end_time']
		return timings 

	@property
	def event(self):
		return self.show.event 

	def __str__(self):
		return 'Slot preference ' + str(self.slot_preference) + ' for ' + str(self.show.show_title) + ' (' + str(self.show.company) + ', ' + str(self.venue.title) + ')'

class Comment(models.Model):
	show = models.ForeignKey(Show, on_delete=models.CASCADE, null=True)
	author = models.ForeignKey('people.Person', on_delete=models.CASCADE)
	date = models.DateField() 
	comment = models.TextField()  
	publish_date = models.DateTimeField()

	def __str__(self):
		return 'Comment from ' + self.author + ' on ' + self.publish_date

class Vote(models.Model):
	show = models.ForeignKey(Show, on_delete=models.CASCADE, null=True)
	score = models.CharField(
		choices = (
			('A+', 'Amazing'),
			('A', 'Bit fine actually')
		),
		default='A',
		max_length=30,
	)
	subject = models.CharField(max_length=180)
	status = models.CharField(
		choices = (
			('M', 'Moral'),
			('T', 'Technical'),
			('A', 'Artistic'),
			('N', 'Note')
		),
		default='N',
		max_length=10
	)
	comment = models.TextField()
	author = models.ForeignKey('people.Person', on_delete=models.CASCADE)

	def __str__(self):
		return self.score + ' by ' + self.author 


class Invoice(models.Model):
	company = models.ForeignKey(Company, null=True, blank=True, on_delete=models.CASCADE)
	show = models.ForeignKey(Show, null=True, blank=True, on_delete=models.CASCADE)
	person = models.ForeignKey('people.Person', null=True, blank=True, on_delete=models.CASCADE)

	invoice_amount = models.DecimalField(null=True, decimal_places=2, max_digits=10)
	invoice_status = models.CharField(max_length=20, choices=(
			('DRAFT', 'Draft'),
			('SENT', 'Sent to recipient'),
			('PAID', 'Paid by recipient')
		), default='DRAFT')
	invoice_date = models.DateField(null=True)

programming/forms.py
from django import forms 

from .models import Show, Event, Company, Slot, Week, Offer
from people.models import Person 

class ShowForm(forms.ModelForm):
	class Meta:
		model = Show 
		fields = ("show_title", "company", "lead_contact", "level",
			"outline", "motivation", "funding",
			"copy_short", "copy_long",
			"set_outline", "tech_outline",
			"cast_size", "crew_size",
			"show_duration", "get_in_dur", "get_out_dur")
		# Company choices limited to companies for which self.user is a member 
		# lead_contacts is limited to self.user AND any company members of the selected company

	def __init__(self, *args, **kwargs):
		# Get the user_profile kwarg from get_form_kwargs in the view, and use it to filter to the user's companies 
		self.user_profile = kwargs.pop('user_profile', None)
		self.site_user = kwargs.pop('site_user', None)
		super(ShowForm, self).__init__(*args, **kwargs)
		self.fields['company'].queryset = Person.objects.filter(site_user=self.site_user).first().get_companies()
		self.fields['lead_contact'].queryset = Person.objects.filter(site_user=self.site_user)

class SlotCreationForm(forms.ModelForm):
	class Meta:
		model = Slot 
		fields = ("venue", "show_start_time", "show_end_time", "slot_preference", "week")

		widgets = {
			'week': forms.CheckboxSelectMultiple(),
		}

	def __init__(self, *args, **kwargs):
		self.show = kwargs.pop('show', None)
		super(SlotCreationForm, self).__init__(*args, **kwargs)
		self.fields['week'].queryset = Week.objects.filter(event=self.show.event).filter(has_performances=True)

class CompanyForm(forms.ModelForm):
	class Meta: 
		model = Company 
		fields = ("company_name", "company_email", "company_website", "lead_contact")

	def __init__(self, *args, **kwargs):
		self.site_user = kwargs.pop('site_user', None)
		super(CompanyForm, self).__init__(*args, **kwargs)
		self.fields['lead_contact'].queryset = Person.objects.filter(site_user=self.site_user)

class OfferForm(forms.ModelForm):
	class Meta:
		model = Offer 
		fields = ("status",)

programming/templates/company-detail.html
{% extends base.html %}

{{ context }}

programming/templates/company-list.html
{% extends base.html %}

{{ context }}

programming/templates/event-shows-all.html
{% extends base.html %}

{{ context }}

programming/templates/event-shows-offers.html
{% extends base.html %}

{{ context }}

programming/templates/index.html
{% extends "base.html" %}
{% block page_content %}

{% if user_profile %}
<div class="container">
	<div class="row">
		<div class="col-12 my-4">
			<h1>Welcome, {{ user_profile }}</h1>
		</div>
	</div>
</div>
{% endif %}

{% if user_profile.person_type == 'STAFF' %}

<div class="container">
	<div class="row">
		<div class="col-12 col-lg-4">
			<div class="card">
				<div class="card-header">
					<p class="h3">Volunteer Application</p>
				</div>
				<div class="card-body">
					{% if user_profile.get_applications %}
						{% for application in user_profile.get_applications %}
							<div class="card">
								<div class="card-header">{{ application }}</div>
								<div class="card-body">
									<p>{{ application.get_status_display }}</p>
									{% if application.offer %}
										<div class='alert alert-info'><h3>Application Offer</h3>
											{% if application.offer.status != 'PEN' %}<p>You have {{ application.offer.get_status_display|lower }} this offer</p>{% endif %}
											<p><a href="{% url 'staffing:staffingApplicationOfferUpdate' application.pk %}">
												{% if application.offer.status == 'PEN' %}
													Review this offer
												{% elif application.offer.status == 'ACC' or application.offer.status == 'REJ' %}
													Change your acceptance of this offer
												{% endif %}
											</a></p>

										</div>
									{% endif %}
								</div>
							</div>
						{% endfor %}
					{% else %}
						<p>You have no previous applications.</p>
					{% endif %}
					<hr>
					{% if available_events %}
						{% if available_event_applications %}
							Make a new application for:
							<ul>
								{% for event in available_event_applications %}
								<li><a href="{% url 'staffing:staffingCreateApplication' event.pk %}">{{ event }}</a></li>
								{% endfor %}
							</ul>
						{% else %}
							<p>You have an application for all available events.</p>
						{% endif %}
					{% else %}
						<p>There are currently no events open for application.</p>
					{% endif %}
				</div>
			</div>
		</div>
		<div class="col-12 col-lg-4">
			<div class="card mb-4">
				<div class="card-header">
					<h3>Quick Links</h3>
				</div>
				<div class="card-body">
					<ul>
					{% for q in quick_links %}
						<li>
							{% if q.link %}<a href="{{ q.link }}">{{ q.title }}</a>
							{% else %}{{ q.title }}{% endif %}
						</li>
					{% empty %}
						<p><em>No quick links have been set up, please contact an IT person.</em></p>
					{% endfor %}
					</ul>
				</div>
			</div>
			{% if user_is_director %}
			<div class="card">
				<div class="card-header"><h3>Director Areas</h3></div>
				<div class="card-body">
					<ul>
						<li><a href="{% url 'staffing:staffingApplicationList' %}">Review volunteer applications</a></li>
						<li><a href="{% url 'programming:programmingShowPending' %}">View shows awaiting offers</a></li>
					</ul>
				</div>
			</div>
			{% endif %}
		</div>
		<div class="col-12 col-lg-4">
			<div class="card">
				<div class="card-header">
					<p class="h3">Programme</p>
				</div>
				<div class="card-body">
					<h4>Shows</h4>
					Members can vote and comment on shows before we programme them for the festival.
					<br><a href="{% url 'programming:programmingShowList' %}">Head to the shows</a>
					<hr>
					<h4>Timeline</h4>
					<p><span>Vertical Timeline</span></p>
					<p><span>Horizontal Timeline (for printing)</span></p>
					<hr>
					<h4>Box Office</h4>
					<small>You'll need your VIA login for these.</small>
					<p><span>VIA homepage</span></p>
					<p><span>VIA Reports</span></p>
				</div>
			</div>
		</div>
	</div>
</div>

{% elif user_profile.person_type == 'COMPY' %}
<div class="container">
	<div class="row">
		<div class="col-12 col-lg-8">
			<div class="card">
				<div class="card-header">
					<h2>Your shows</h2>
				</div>
				<div class="card-body">
					{% if user_profile.get_shows %}
						{% if user_profile.get_shows.lead %}
						<p class="lead">You are the lead contact on:</p>
						<ul>
							{% for s in user_profile.get_shows.lead %}
							<li><a href="{% url 'programming:programmingShowDetail' s.pk %}">{{ s }}</a></li>
							{% endfor %}
						</ul>
						{% endif %}
						{% if user_profile.get_shows.listed %}
						<p class="lead">You are on the team for:</p>
						<ul>
							{% for s in user_profile.get_shows.listed %}
							<li><a href="{% url 'programming:programmingShowDetail' s.pk %}">{{ s }}</a></li>
							{% endfor %}
						</ul>
						{% endif %}
					{% else %}
						<p>
							You don't have any shows yet.
						</p>
					{% endif %}
						<hr>
						<p>{% if available_events %}
						We are accepting submissions for {% for e in available_events %}<a href="{% url 'programming:programmingCreateShow' e.pk %}">{{ e }}</a>{% if not forloop.last %}, {% endif %}{% endfor %}
						{% else %}
						We are not currently accepting applications. Please contact us if you think this is an error.
						{% endif %}</p>
				</div>
			</div>
		</div>
		<div class="col-12 col-lg-4">
			<div class="card">
				<div class="card-header">
					<h3>Need help?</h3>
				</div>
				<div class="card-body">
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
					tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
					quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
					consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
					cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
					proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
				</div>
			</div>
		</div>
	</div>
</div>
{% else %}

Your profile hasn't been setup properly. Please contact an IT person.
	
{% endif %}

{% endblock %}

programming/templates/invoice-company.html
{% extends base.html %}

{{ context }}

programming/templates/invoice-list.html
{% extends base.html %}

{{ context }}

programming/templates/show_detail.html
{% extends 'base.html' %}

{% block page_title %}{{ show.show_title }}{% endblock %}

{% block page_content %}

<div class="container">
	<div class="row">
		<div class="col-12">
			<h1 class="text-center">{{ show }}</h1>
		</div>
	</div>
	<div class="row my-4">
		<div class="col-12 col-md-8">
			<div class="card">
				<div class="card-header">
					<h2>Show Information {% if can_edit %}<a href="{% url 'programming:programmingShowUpdate' show.pk %}" class="btn btn-primary">Edit</a>{% endif %}</h2>
				</div>
				<div class="card-body">
					<p>Outline: {{ show.outline }}</p>
					<p>Motivation: {{ show.motivation }}</p>
					<p>Funding: {{ show.funding }}</p>
					<h2>Marketing Information</h2>
					<p>Marketing Copy (Short): {{ show.marketing_copy_short }}</p>
					<p>Marketing Copy (Long): {{ show.marketing_copy_long }}</p>
					<h2>Backstage Information</h2>
					<p>Set outline: {{ show.set_outline }}</p>
					<p>Tech outline: {{ show.tech_outline }}</p>
					<h2>People</h2>
					<p>Cast size: {{ show.cast_size }}</p>
					<p>Crew size: {{ show.crew_size }}</p>
					<h2>Timings</h2>
					<p>Duration: {{ show.duration }}</p>
					<p>Get-In: {{ show.get_in_dur }}</p>
					<p>Get-Out: {{ show.get_out_dur }}</p>
				</div>
			</div>
		</div>
		<div class="col-12 col-md-4">
			<div class="card mb-4">
				<div class="card-header">
					<h2>Application Status</h2>
				</div>
				<div class="card-body">
					<p>{{ show.get_status_display }}</p>
					{% if show.offer %}
						<div class="alert alert-info">
							<h3>Offer</h3>
							<p>{{ show.offer }}</p>
							{% if user_profile.person_type == 'COMPY' %}
								<a href="{% url 'programming:programmingOfferUpdate' show.pk %}">
									{% if show.offer.status == 'PEN' %}Accept or reject this offer 
									{% elif show.offer.status == 'ACC' %}Withdraw this offer
									{% elif show.offer.status == 'REJ' %}Accept this offer{% endif %}
								</a>

							{% elif user_profile.person_type == 'STAFF' %}
								{% if show.offer.status == 'PEN' %}<p><em>Waiting on the company...</em></p>{% endif %}
							{% endif %}
						</div>
					{% endif %}
				</div>
			</div>
			<div class="card">
				<div class="card-header">
					<h2>Company Information {% if can_edit and show.company %}<a class="btn btn-primary" href="{% url 'programming:programmingCompanyForm' show.company.pk %}">Edit</a>{% endif %}</h2>
				</div>
				<div class="card-body">
					<p>Company name: {{ show.company }}</p>
					<p>Lead contact: {{ show.lead_contact }}</p>
					<p>Company level: {{ show.get_level_display }}</p>
				</div>
			</div>
		</div>
	</div>
	<div class="row my-4">
		<div class="col-12">
			<div class="card">
				<div class="card-header">
					<h2>Slots</h2>
				</div>
				<div class="card-body">
					{% if show.get_slots %}
						<table class="table table-condensed">
							<thead>
								<tr>
									<th>Preference</th>
									<th>Venue</th>
									<th>Slot start</th>
									<th>Show start</th>
									<th>Show end</th>
									<th>Slot end</th>
									<th></th>
								</tr>
							</thead>
							<tbody>
							{% for slot in show.get_slots %}
								<tr>
									<td># {{ slot.slot_preference }}</td>
									<td>{{ slot.venue }}</td>
									<td>{{ slot.slot_timings.slot_start_time | date:"G:i" }}</td>
									<td>{{ slot.show_start_time }}</td>
									<td>{{ slot.show_end_time }}</td>
									<td>{{ slot.slot_timings.slot_end_time | date:"G:i" }}</td>
									<td>Move Up / Down</td>
								</tr>
							</tbody>
							{% endfor %}
						</table>
					{% endif %}
					{% if can_edit %}<p><a href="{% url 'programming:programmingSlotCreation' show.pk %}">Add a slot</a></p>{% endif %}
				</div>
			</div>
		</div>
	</div>
	{% if user_profile.person_type == 'STAFF' %}
	<div class="row my-4">
		<div class="col-12 col-lg-6">
			<div class="card">
				<div class="card-header">
					<h2>Votes</h2>
				</div>
				<div class="card-body">
					<p>{{ show.get_votes }}</p>
				</div>
			</div>
		</div>
		<div class="col-12 col-lg-6">
			<div class="card">
				<div class="card-header">
					<h2>Comments</h2>
				</div>
				<div class="card-body">
					<p>{{ show.get_comments }}</p>
				</div>
			</div>
		</div>
	</div>
	{% endif %}
</div>

{% endblock %}