people/urls.py
from django.urls import path 
from . import views 

app_name = 'people' 

urlpatterns = [ 
	path('person/', views.PersonDetailView.as_view(), name='personDetail'),
	path('person/setup/', views.PersonCreateView.as_view(), name='personSetUp'),
	path('person/edit/', views.PersonUpdateView.as_view(), name='personUpdate'),
]

pgp_mis/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url 
from . import views 

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('programming.urls')),
    url(r'^', include('people.urls')),
    url(r'^', include('staffing.urls')),
    path('', include('django.contrib.auth.urls')),
    path('register/', views.UserRegisterView.as_view(), name='userRegister'),
]

admin.site.site_header = "Paradise MIS Admin"
admin.site.site_title = "Paradise Green MIS 2.0"
admin.site.index_title = "Paradise Green MIS 2.0"

programming/urls.py
from django.urls import path 
from . import views 

app_name = 'programming' 

urlpatterns = [ 

	path('', views.HomeView.as_view(), name='programmingDashboard'),
	path('shows/', views.ShowListView.as_view(), name='programmingShowList'), # Uses the "current" Event 
	path('shows/pending/', views.ShowListPendingView.as_view(), name='programmingShowPending'),
	path('shows/<int:pk>/', views.ShowDetailView.as_view(), name='programmingShowDetail'),
	path('shows/<int:pk>/edit/', views.ShowUpdateView.as_view(), name='programmingShowUpdate'),

	path('shows/<int:pk>/newslot/', views.SlotCreateView.as_view(), name='programmingSlotCreation'),
	path('shows/<int:pk>/slots/', views.SlotListView.as_view(), name='programmingSlotList'),

	path('shows/<int:pk>/<int:slot_pk>/offer/', views.OfferCreateView.as_view(), name='programmingSlotOffer'),
	path('shows/<int:pk>/offer/', views.OfferUpdateView.as_view(), name='programmingOfferUpdate'),
	# path('shows/<int:pk>/offer/confirm/', views.SlotOfferConfirm.as_view(), name='programmingSlotOfferConfirm'),
	
	path('companies/', views.CompanyListView.as_view(), name='programmingCompanyList'),
	path('companies/<int:pk>/', views.CompanyDetailView.as_view(), name='programmingCompanyDetail'),
	path('companies/<int:pk>/edit/', views.CompanyFormView.as_view(), name='programmingCompanyForm'),
	path('companies/<int:pk>/invoices/', views.CompanyInvoiceView.as_view(), name='programmingCompanyInvoice'),
	
	path('invoices/', views.InvoiceListView.as_view(), name='programmingInvoiceList'),
	path('invoices/<int:pk>/', views.InvoiceDetailView.as_view(), name='programmingInvoiceDetail'),
	
	path('event/', views.EventListView.as_view(), name='programmingEventList'), # Lists all events for archive use 
	path('event/<int:pk>/', views.ShowListView.as_view(), name='programmingEventDetail'), # Same as programmingShowList but specific Event
	path('event/<int:pk>/all/', views.EventAllView.as_view(), name='programmingEventAll'),
	
	path('event/<int:pk>/perform/', views.ShowCreateView.as_view(), name='programmingCreateShow'),
	# shows/ 
	# show/<int:pk>
		# with functionality to view their slot preferences and make them an offer 
		# with functionality to view a list of invoices associated with the show 
		# with functionality to do comments / voting 
	# companies/
	# companies/<int:pk>/
	# companies/<int:pk/invoices/ - invoices for a given company 
	# invoices/ 
	# invoices/<int:pk>/ - specific invoices 
	# event/ - event list 
	# event/<int:pk>/ - shows that have been offered a slot 
	# event/<int:pk>/all/ - all shows registered with the event
]

templates/base.html
<!doctype html>
<html lang="en" class="h-100">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>{% block page_title %}{% if page_title %}{{ page_title }} | Paradise Green MIS {% else %}Paradise Green MIS{% endif %}{% endblock page_title %}</title>
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
	</head>
	<body class="h-100 d-flex flex-column">
		<div class="container-fluid">
			<div class="row mb-4">
				<div class="col-12 px-0">
					<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
						<div class="container-fluid">
							<a class="navbar-brand" href="{% url 'programming:programmingDashboard' %}">Paradise Green MIS</a>
							<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#pgp_mis_navbar" aria-controls="pgp_mis_navbar" aria-expanded="false" aria-label="Toggle navigation">
								<span class="navbar-toggler-icon"></span>
							</button>
							<div class="collapse navbar-collapse" id="pgp_mis_navbar">
								<ul class="navbar-nav me-auto mb-2 mb-lg-0">
									{% if user_profile %}
									<span class="navbar-text text-light pe-4">{{ user_profile }}</span>
									<li class="nav-item">
										<a class="nav-link" aria-current="page" href="{% url 'programming:programmingDashboard' %}">{% if user_profile.person_type == 'COMPY' %}Company {% else %}Volunteer {% endif %}Dashboard</a>
									</li>
									{% endif %}
									{% if user_profile and user_profile.person_type == 'STAFF' %}
									<li class="nav-item">
										<a class="nav-link" href="#">Programming</a>
									</li>
									<li class="nav-item">
										<a class="nav-link" href="#">Staffing</a>
									</li>
									<li class="nav-item">
										<a class="nav-link" href="#">Technical Paperwork</a>
									</li>
									<li class="nav-item dropdown">
										<a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
											Dropdown
										</a>
										<ul class="dropdown-menu">
											<li><a class="dropdown-item" href="#">Action</a></li>
											<li><a class="dropdown-item" href="#">Another action</a></li>
											<li><hr class="dropdown-divider"></li>
											<li><a class="dropdown-item" href="#">Something else here</a></li>
										</ul>
									</li>
									{% endif %}
									{% if user.is_authenticated %}
									<li class="nav-item">
										<a class="nav-link" href="{% url 'logout' %}">Logout</a>
									</li>
									{% endif %}
								</ul>
							</div>
						</div>
					</nav>
				</div>
			</div>
		</div>
		{% if messages or exception %}
		<div class="container">
			{% for message in messages %}
				<div class="alert {% if message.tags == 'error' %}alert-danger {% else %}alert-{{ message.tags }} {% endif %} alert-dismissable fade show" role="alert">
					<p><button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
					{% if message.tags == 'error' %}<i class="fa fa-fw fa-exclamation-circle"></i>&nbsp;
					{% else %}<i class="fa fa-fw fa-info-circle"></i>&nbsp;
					{% endif %}
					{{ message }}</p>
				</div>
			{% endfor %}
			{% if exception %}
				<div class="alert alert-danger alert-dismissable fade show" role="alert">
					<p><button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
					{% if message.tags == 'error' %}<i class="fa fa-fw fa-exclamation-circle"></i>&nbsp;
					{% else %}<i class="fa fa-fw fa-info-circle"></i>&nbsp;
					{% endif %}
					{{ exception }}</p>
				</div>
			{% endif %}
		</div>
		{% endif %}
		{% block page_content %}
			<div class="container">
				<div class="row">
					<div class="col-12">
						<p class="text-center my-4"><i>No content defined for this page (yet!)</i></p>
					</div>
				</div>
			</div>
		{% endblock page_content %}

		{% block footer %}
		<div class="spacer my-3"></div>
		<div class="container-fluid bg-secondary mt-auto">
			<div class="row">
				<div class="col-12 text-center py-2">
					<p><small>&copy; Paradise Green</small></p>
				</div>
			</div>
		</div>
		{% endblock %}
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
	</body>
</html>

templates/register.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block page_content %}

<div class="container">
	{% if user.is_authenticated %}
		<div class="row">
			<div class="col-12 col-md-10 col-lg-8 offset-md-1 offset-lg-2">
				<h1>You are already registered</h1>
				<p>Let's try going back to the <a href="{% url 'programming:programmingDashboard' %}">dashboard</a></p>
			</div>
		</div>
	{% else %}
		<div class="row">
			<div class="col-12 col-md-10 col-lg-8 offset-md-1 offset-lg-2">
				<h1>Register</h1>

				<form method="post" action="{% url 'userRegister' %}">
					{% csrf_token %}
					{% for field in form %}
						<div class="row form-group mb-2">
							<div class="col-12 mx-auto">
								{% if field.errors %}<div class="alert alert-danger">{{ field.errors.as_ul }}</div>{% endif %}
								{{ field.help_text }}
								<div class="text-left text-primary">{{ field.label_tag|title }}</div>
								{% render_field field class+="form-control" placeholder+=field.label %}
							</div>
						</div>
					{% endfor %}

					<div class="row my-2">
						<div class="col-12 col-sm-10 col-lg-8 mx-auto">
						<button type="submit" value="login" class="btn btn-primary btn-lg w-100">Register</button>
						<input type="hidden" name="next" value="{{ next }}" />
						</div>
					</div>

				</form>
			</div>
		</div>
	{% endif %}
</div>

{% endblock %}