people/urls.py
from django.urls import path 
from . import views 

app_name = 'people' 

urlpatterns = [ 
	path('person/', views.PersonDetailView.as_view(), name='personDetail'),
	path('person/setup/', views.PersonCreateView.as_view(), name='personSetUp'),
	path('person/edit/', views.PersonUpdateView.as_view(), name='personUpdate'),
]

pgp_mis/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url 
from . import views 

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('programming.urls')),
    url(r'^', include('people.urls')),
    url(r'^', include('staffing.urls')),
    path('', include('django.contrib.auth.urls')),
    path('register/', views.UserRegisterView.as_view(), name='userRegister'),
]

admin.site.site_header = "Paradise MIS Admin"
admin.site.site_title = "Paradise Green MIS 2.0"
admin.site.index_title = "Paradise Green MIS 2.0"

staffing/urls.py
from django.urls import path 
from . import views 


app_name = 'staffing' 

urlpatterns = [ 
	
	path('event/<int:pk>/volunteer/', views.ApplicationFormView.as_view(), name='staffingCreateApplication'),
	path('applications/', views.ApplicationListView.as_view(), name='staffingApplicationList'), # current event 
	path('applications/<int:pk>/', views.ApplicationDetailView.as_view(), name='staffingApplicationDetail'),
	path('applications/<int:pk>/offer/', views.OfferFormView.as_view(), name='staffingApplicationOfferCreate'),
	path('applications/<int:pk>/review/', views.OfferUpdateView.as_view(), name='staffingApplicationOfferUpdate'),
	# path('event/<int:pk>/applications', views.ApplicationListView.as_view(), name='staffingAppliationListArchive'),

]

staffing/models.py
from django.db import models

# Create your models here.

class StaffRole(models.Model):
	class Meta: 
		ordering = ['department','role_name']
	role_name = models.CharField(max_length=100, blank=True, unique=True, help_text="A role offered on the staff, eg. Technician")
	department = models.CharField(max_length=50, 
		choices = (
			('H', 'Front of House'),
			('K', 'Kitchen'),
			('T', 'Technical'),
			('A', 'Administration'),
			('D', 'Duty')
		),
		default='H')
	is_management = models.BooleanField(default=False)
	appears_in_application = models.BooleanField(default=True, help_text="Deselect for special roles only appearing on the rota and not selectable in the volunteer application form, eg. 'Other', 'Build Manager', etc.")

	def __str__(self):
		return self.role_name

class Application(models.Model):
	class Meta:
		permissions = [
			('dir_can_offer_application', 'Can review and offer applications')
		]
		verbose_name = 'Volunteer Application'
		verbose_name_plural = 'Volunteer Applications'
		unique_together = ['person','event_application']
		# A person may only have one application for a particular event
		# TODO: Unique together: roles_willing, roles_desired, roles_declined
		# Not currently implemented because nice error handling would be a fine thing 

	person = models.ForeignKey('people.Person', on_delete=models.CASCADE, null=True)
	# This is a ForeignKey because a person can have applications with multiple events
	roles_willing = models.ManyToManyField(StaffRole, related_name='roles_willing', blank=True)
	roles_desired = models.ManyToManyField(StaffRole, related_name='roles_desired', blank=True)
	roles_declined = models.ManyToManyField(StaffRole, related_name='roles_declined', blank=True)

	person_bio = models.TextField()
	event_application = models.OneToOneField('programming.Event', on_delete=models.SET_NULL, null=True)
	weeks_available = models.ManyToManyField('programming.Week')
	status = models.CharField(max_length=30,
		choices = (
			('ACC', 'Offer accepted'),
			('OFF', 'Offer made'),
			('REJ', 'Offer rejected'),
			('APP', 'Application complete'),
			('INC', 'Application started'),
			('WIT', 'Application withdrawn')
		),
		default='INC',
		verbose_name='Application status',
	)

	@property 
	def long_name(self):
		return self + ' for ' + str(self.person)

	@property 
	def has_management_roles(self):
		for role in self.roles_desired.all():
			if role.is_management:
				return True 
		for role in self.roles_willing.all():
			if role.is_management:
				return True 
		return False 

	def __str__(self):
		return str(self.person) + ' application for ' + str(self.event_application) 

class WeekPreference(models.Model):
	class Meta:
		ordering = ['order']

	application = models.ForeignKey(Application, on_delete=models.CASCADE, null=True)
	weeks = models.ManyToManyField('programming.Week')
	order = models.IntegerField(unique=True)

class Offer(models.Model):
	class Meta:
		verbose_name = 'Volunteer Offer'
		verbose_name_plural = 'Volunteer Offers'

	application = models.OneToOneField(Application, on_delete=models.CASCADE)
	weeks = models.ManyToManyField('programming.Week')
	status = models.CharField(max_length=10,
		choices = (
			('PEN', 'Pending'),
			('ACC', 'Accepted'),
			('REJ', 'Rejected'),
		),
		default = 'PEN'
	)	

	def __str__(self):
		return 'Offer for ' + str(self.application.person) + ' (' + str(self.get_status_display()) + ', ' + str(self.application.event_application) + ')'

class QuickLink(models.Model):
	class Meta:
		ordering = ['ordering']
		verbose_name = 'Quick Link'
		verbose_name_plural = 'Quick Links'

	title = models.CharField(max_length=100,blank=True, help_text='How the link appears, eg "Rota"')
	link = models.URLField(blank=True, help_text="The full link to the page, don't forget the https://!")
	ordering = models.IntegerField(default=1)

	def __str__(self):
		return 'Quick link for ' + self.title

staffing/forms.py
from django import forms 
from django.utils.text import slugify 

from .models import Application, StaffRole, Offer
from people.models import Person 
from programming.models import Event, Week

class ApplicationForm(forms.ModelForm):
	# Staffing application form (company / show applications are in the programming app)
	class Meta:
		model = Application 
		fields = ("roles_willing", "roles_desired", "roles_declined",
			"person_bio", "weeks_available")
		widgets = {
			'roles_willing': forms.CheckboxSelectMultiple(),
			'roles_desired': forms.CheckboxSelectMultiple(),
			'roles_declined': forms.CheckboxSelectMultiple(),
			'weeks_available': forms.CheckboxSelectMultiple(), 
		}

	def __init__(self, *args, **kwargs):
		# Get the user_profile kwarg from get_form_kwargs in the view, and use it to filter to the user's companies 
		self.event = kwargs.pop('event', None)
		super(ApplicationForm, self).__init__(*args, **kwargs)
		self.fields['weeks_available'].queryset = Week.objects.filter(event=self.event)
		self.fields['roles_willing'].queryset = StaffRole.objects.filter(appears_in_application=True)
		self.fields['roles_desired'].queryset = StaffRole.objects.filter(appears_in_application=True)
		self.fields['roles_declined'].queryset = StaffRole.objects.filter(appears_in_application=True)

		'''
		## Manually add a bunch of custom fields for the available roles
		# for role in StaffRole.objects.filter(appears_in_application=True):
		# 	self.fields[slugify(str(role.role_name))] = forms.ChoiceField(
		# 		label=str(role.role_name),
		# 		choices = (
		# 			('1', 'I would not like to do this role'),
		# 			('2', 'I can do this role if required'),
		# 			('3', 'I would like to do this role')
		# 		),
		# 	)
		'''

class OfferForm(forms.ModelForm):
	class Meta:
		model = Offer 
		fields = ('weeks', 'status')
		widgets = {
			'weeks': forms.CheckboxSelectMultiple(),
		}

	def __init__(self, *args, **kwargs):
		self.event = kwargs.pop('event', None)
		super(OfferForm, self).__init__(*args, **kwargs)
		self.fields['weeks'].queryset = Week.objects.filter(event=self.event)

staffing/views.py
from django.contrib import messages 
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin, PermissionRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.core.exceptions import PermissionDenied
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView, UpdateView, FormView

from programming.models import Event 
from staffing.models import Application, QuickLink, Offer
from .forms import ApplicationForm, OfferForm 

from programming.mixins import MISPermissionMixin, get_user_profile

# Views for the app and its models 

class ApplicationFormView(PermissionRequiredMixin, MISPermissionMixin, SuccessMessageMixin, CreateView):
# passes test: can edit company (directors; company)
	permission_required = ('staffing.add_application')
	template_name = 'application_form.html'
	success_url = reverse_lazy('programming:programmingDashboard')
	form_class = ApplicationForm 
	success_message = "Application submitted successfully"
	model = Application 	

	def get_object(self, **kwargs):
		return Event.objects.get(pk=self.kwargs['pk'])

	def get_context_data(self, **kwargs):
		context = super().get_context_data()
		context['event'] = Event.objects.get(pk=self.kwargs['pk'])
		return context 

	def get_form_kwargs(self):
		kwargs = super().get_form_kwargs()
		kwargs['event'] = self.kwargs['pk']
		return kwargs 

	def form_valid(self, form):
		# Manually assign the Application to the Person  
		form.instance.person = get_user_profile(self.request.user)
		form.instance.event_application = Event.objects.get(pk=self.kwargs['pk'])
		return super().form_valid(form)

class ApplicationListView(PermissionRequiredMixin, MISPermissionMixin, generic.ListView):
	permission_required = ('staffing.change_application', 'staffing.dir_can_offer_application')
	permission_denied_message = "Only directors can view applications"
	model = Application 
	template_name = 'application_list.html'
	context_object_name = 'applications'

	def get_context_data(self, **kwargs):
		context = super().get_context_data()
		if self.kwargs and self.kwargs['pk']:
			context['event'] = Event.objects.get(pk=self.kwargs['pk'])
		else:
			context['event'] = Event.objects.last() 
		return context 

class ApplicationDetailView(MISPermissionMixin, PermissionRequiredMixin, generic.DetailView):
	permission_required = ('staffing.view_application')
	model = Application 
	template_name = "application_detail.html"

class OfferFormView(MISPermissionMixin, PermissionRequiredMixin, generic.CreateView):
	permission_required = ('staffing.add_offer',)
	template_name = 'application_offer_form.html'
	model = Application 
	form_class = OfferForm
	success_url = reverse_lazy('staffing.staffingApplicationList')

	def dispatch(self, *args, **kwargs):
		if Offer.objects.filter(application=Application.objects.get(pk=self.kwargs['pk'])):
			messages.add_message(self.request, messages.ERROR, "This application already has an offer attached")
			return redirect(reverse_lazy('staffing:staffingApplicationDetail', kwargs={'pk': self.kwargs['pk'] }))
		else: 
			return super(OfferFormCreateView, self).dispatch(*args, **kwargs)

	def get_form_kwargs(self):
		kwargs = super().get_form_kwargs()
		kwargs['event'] = Application.objects.get(pk=self.kwargs['pk']).event_application
		return kwargs 

	def form_valid(self, form):
		# Manually assign the Application to the Person  
		form.instance.application = Application.objects.get(pk=self.kwargs['pk'])
		form.instance.status = 'PEN'
		return super().form_valid(form)

	def get_context_data(self, **kwargs):
		context = super().get_context_data()
		context['create'] = True 
		context['application'] = Application.objects.get(pk=self.kwargs['pk'])
		return context 

class OfferUpdateView(MISPermissionMixin, PermissionRequiredMixin, generic.UpdateView):
	permission_required = ('staffing.change_offer')
	template_name = 'application_offer_form.html' 
	model = Offer 
	form_class = OfferForm 
	success_url = reverse_lazy('programming:programmingDashboard')

	def get_form_kwargs(self):
		kwargs = super().get_form_kwargs()
		kwargs['event'] = Application.objects.get(pk=self.kwargs['pk']).event_application
		return kwargs 

	def get_object(self, **kwargs):
		try:
			return Offer.objects.get(application=Application.objects.get(pk=self.kwargs['pk']))
		except:
			messages.add_message(self.request, messages.ERROR, "There is no offer currently attached to this application.")
			raise Http404

	def get_context_data(self, **kwargs):
		context = super().get_context_data()
		context['application'] = Application.objects.get(pk=self.kwargs['pk'])
		context['offer'] = context['application'].offer 
		return context 

	def form_valid(self, form):
		form.instance.weeks.set = Offer.objects.get(application=Application.objects.get(pk=self.kwargs['pk'])).weeks
		return super().form_valid(form)

staffing/templates/application_detail.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block page_title %}Application Form - {{ application.person }}{% endblock %}

{% block page_content %}
<div class="container">
	<div class="row">
		<div class="col-12 col-lg-10 offset-lg-1">
			<h1>Application: {{ application }}</h1>
			<p>Name: {{ application.person }}</p>
			<p class="lead">About {{ application.person }}</p>
			<p class="ms-4">{{ application.person_bio }}</p>
			<hr>
			<p class="lead">Roles</p>
			<p>Selected management roles: {{ application.has_management_roles|yesno:"Yes,No" }}</p>
			<table class="table">
				<thead>
					<tr>
						<th>Roles Desired</th>
						<th>Roles Willing</th>
						<th>Roles Undesired</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>{{ application.roles_desired.all|join:", <br>" | default:"None" }}</td>
						<td>{{ application.roles_willing.all|join:", <br>" | default:"None"}}</td>
						<td>{{ application.roles_declined.all|join:", <br>" | default:"None"}}</td>
					</tr>
				</tbody>
			</table>
			<p class="lead">Availability</p>
			<p>{{ application.weeks_available.all|join:"<br>" }}</p>
		</div>
	</div>
	{% if user_is_director %}
	<div class="row">
		<div class="col-12 col-md-10 col-lg-8 offset-md-1 offset-lg-2">
			{% if application.offer %}
				<h3>Offer</h3>
				{{ application.offer }}
			{% else %}
				<p class="text-center"><a class="btn btn-success w-75 btn-lg" href="{% url 'staffing:staffingApplicationOfferCreate' application.pk %}">Make an offer</a></p>
			{% endif %}
		</div>
	</div>
	{% endif %}

	{% if form %}
	<div class="row">
			<form method="post" action="">
				{% csrf_token %}
				{% if create %}
					<div class="d-none">{{ form.as_p }}</div>
				{% else %}
					{% for field in form %}
						<div class="row form-group mb-2">
							<div class="col-12 mx-auto">
								<div class="text-left text-primary">Accept or reject using the menu below</div>
								{% if field.errors %}<div class="alert alert-danger">{{ field.errors.as_ul }}</div>{% endif %}
								{{ field.help_text }}
								{% render_field field class+="form-control" placeholder+=field.label %}
							</div>
						</div>
					{% endfor %}
				{% endif %}

				<div class="row my-2">
					<div class="col-12 col-sm-10 col-lg-8 mx-auto">
					<button type="submit" value="submit" class="btn btn-success btn-lg w-100">
						{% if create %}Make the offer{% else %}Save{% endif %}</button>
					<input type="hidden" name="next" value="{{ next }}" />
					</div>
				</div>
			</form>
		</div>
	</div>
	{% endif %}
</div>

{% endblock %}

staffing/templates/application_form.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block page_title %}Application Form{% endblock %}

{% block page_content %}
<div class="container">
	<div class="row">
		<div class="col-12 col-lg-10 offset-lg-1">
			<h1>Volunteer Application for {{ event }} for {{ user_profile }}</h1>
		</div>
	</div>
	<div class="row">
		<div class="col-12 col-lg-10 offset-lg-1">
			{{ form.errors }}
			<form method="post" action="">
				{% csrf_token %}
				<div class="row">
					<div class="col-12">
						<div class="card">
							<div class="card-header">
								<h2>Roles</h2>
							</div>
							<div class="card-body">
								<div class="row">
									<div class="col-12 col-lg-4 mb-4 mb-lg-2">
										<div class="card">
											<div class="card-header">
												<h3>Roles you would like to do</h3>
											</div>
											<div class="card-body">
												{% if form.roles_desired.errors %}<div class="alert alert-danger">{{ form.roles_desired.errors.as_ul }}</div>{% endif %}
												{% for role in form.roles_desired %}
													<div class="form-check">
													  <input class="form-check-input" name="roles_desired" type="checkbox" value="{{ forloop.counter }}" id="role-desired-{{ forloop.counter }}" {% if role.data.selected %}checked{% endif %}>
													  <label class="form-check-label" for="role-desired-{{ forloop.counter }}">
													    {{ role.choice_label }}
													  </label>
													</div>
												{% endfor %}
											</div>
										</div>
									</div>
									<div class="col-12 col-lg-4 mb-4 mb-lg-2">
										<div class="card">
											<div class="card-header">
												<h3>Roles you would can do if needed</h3>
											</div>
											<div class="card-body">
												{% if form.roles_willing.errors %}<div class="alert alert-danger">{{ form.roles_willing.errors.as_ul }}</div>{% endif %}
												{% for role in form.roles_willing %}
													<div class="form-check">
													  <input class="form-check-input" name="roles_willing" type="checkbox" value="{{ forloop.counter }}" id="role-willing-{{ forloop.counter }}" {% if role.data.selected %}checked{% endif %}>
													  <label class="form-check-label" for="role-willing-{{ forloop.counter }}">
													    {{ role.choice_label }}
													  </label>
													</div>
												{% endfor %}
											</div>
										</div>
									</div>
									<div class="col-12 col-lg-4 mb-4 mb-lg-2">
										<div class="card">
											<div class="card-header">
												<h3>Roles you would <strong>not</strong> like to do</h3>
											</div>
											<div class="card-body">
												{% if form.roles_declined.errors %}<div class="alert alert-danger">{{ form.roles_declined.errors.as_ul }}</div>{% endif %}
												{% for role in form.roles_declined %}
													<div class="form-check">
													  <input class="form-check-input" name="roles_declined" type="checkbox" value="{{ forloop.counter }}" id="role-declined-{{ forloop.counter }}" {% if role.data.selected %}checked{% endif %}>
													  <label class="form-check-label" for="role-declined-{{ forloop.counter }}">
													    {{ role.choice_label }}
													  </label>
													</div>
												{% endfor %}
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<hr>
				<div class="row">
					<div class="col-12">
						<h3>Tell us a bit about yourself</h3>
					</div>
				</div>
				<div class="row mb-2">
					<div class="col-12 mx-auto">
						{% if form.person_bio.errors %}<div class="alert alert-danger">{{ form.person_bio.errors.as_ul }}</div>{% endif %}
						{% render_field form.person_bio class+="form-control" placeholder+=form.person_bio.label %}
					</div>
				</div>
				<div class="row">
					<div class="col-12">
						<h3>Which weeks are you available?</h3>
					</div>
				</div>
				<div class="row mb-2">
					<div class="col-12 mx-auto">
						{% if form.weeks_available.errors %}<div class="alert alert-danger">{{ form.weeks_available.errors.as_ul }}</div>{% endif %}
						{% for week in form.weeks_available %}
							<div class="form-check">
							  <input class="form-check-input" name="weeks_available" type="checkbox" value="{{ forloop.counter }}" id="week-{{ forloop.counter }}" {% if week.data.selected %}checked{% endif %}>
							  <label class="form-check-label" for="week-{{ forloop.counter }}">
							    {{ week.choice_label }}
							  </label>
							</div>
						{% endfor %}
					</div>
				</div>

				<div class="row my-4">
					<div class="col-12 col-sm-10 col-lg-8 mx-auto">
					<button type="submit" value="login" class="btn btn-primary btn-lg w-100">{% if form.instance.person %}Update{% else %}Submit{% endif %}</button>
					<input type="hidden" name="next" value="{{ next }}" />
					</div>
				</div>
			</form>
		</div>
	</div>
</div>

{% endblock %}

staffing/templates/application_list.html
{% extends 'base.html' %}
{% block page_title %}Application Form{% endblock %}

{% block page_content %}
<div class="container">
	<div class="row">
		<div class="col-12 col-lg-10 offset-lg-1">
			<h1>Volunteer Applications for {{ event }}</h1>
			<table class="table table-condensed">
				<thead>
					<tr>
						<td>Name</td>
						<td>Roles desired</td>
						<td>Roles willing</td>
						<td>Has management roles</td>
						<td>Make offer</td>
					</tr>
				</thead>
				<tbody>
					{% for app in applications %}
						<tr>
							<td>{{ app.person }}</td>
							<td>{{ app.roles_desired.all|join:", "}}</td>
							<td>{{ app.roles_willing.all|join:", " }}</td>
							<td>{{ app.has_management_roles|yesno:"Yes,No" }}</td>
							<td>Application: {{ app.get_status_display }} 
								<br>Offer: {{ app.offer.get_status_display }}
								<br><a href="{% url 'staffing:staffingApplicationDetail' app.pk %}">Review Application</a></td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</div>
</div>

{% endblock %}

staffing/templates/application_offer_form.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block page_title %}Offer Confirmation{% endblock %}

{% block page_content %}
<div class="container">
	<div class="row">
		<div class="col-12 col-md-10 col-lg-8 offset-md-1 ">
			<h1>{% if create %}Make an offer{% else %}Offer Confirmation{% endif %}<br>
				<small>{{ application }}</small>
			</h1>
		</div>
	</div>
	<div class="row">
		<div class="col-12 col-lg-10 offset-lg-1">
			<form method="post" action="">
				{% csrf_token %}
				{{ form.errors }}
			{% if create %}
				<h3>Applied Availability:</h3>
				{{ application.weeks_available.all|join:", <br>" }}

				<h3>Offer weeks:</h3>
				{{ form.as_table }} 

			{% else %}
				{% if user_is_director %}
					<p><strong>You are authorised to accept this offer on behalf of the volunteer. Typically this is something the volunteer should do, so please exercise discretion.</strong></p>
				{% endif %}

				<p>You have been offered the following:</p>
				<p>{{ offer.weeks.all|join:", <br>" }}</p>

				<div class="row form-group mb-2">
					<div class="col-12 mx-auto">
						<div class="text-left text-primary">Accept or reject using the menu below</div>
						{% if field.errors %}<div class="alert alert-danger">{{ field.errors.as_ul }}</div>{% endif %}
						{{ field.help_text }}
						{% render_field form.status class+="form-control" placeholder+=field.label %}
						<div class="d-none">{{ form.weeks }}</div>
					</div>
				</div>
			{% endif %}

				<div class="row my-2">
					<div class="col-12 col-sm-10 col-lg-8 mx-auto">
					<button type="submit" value="login" class="btn btn-success btn-lg w-100">
						{% if create %}Make the offer{% else %}Save{% endif %}</button>
					<input type="hidden" name="next" value="{{ next }}" />
					</div>
				</div>

			</form>
		</div>
	</div>
</div>
{% endblock %}